//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ui_kalbe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Penjualans = new HashSet<Penjualan>();
        }
    
        public int intCustomerID { get; set; }
        public string txtCustomerName { get; set; }
        public string txtCustomerAddress { get; set; }
        public Nullable<bool> bitGender { get; set; }
        public Nullable<System.DateTime> dtmBirthDate { get; set; }
        public Nullable<System.DateTime> Inserted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Penjualan> Penjualans { get; set; }
    }
}
