//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ui_kalbe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Penjualan
    {
        public int intSalesOrderID { get; set; }
        public Nullable<int> intCustomerID { get; set; }
        public Nullable<int> intProductID { get; set; }
        public Nullable<System.DateTime> dtSalesOrder { get; set; }
        public Nullable<double> intQty { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Produk Produk { get; set; }
    }
}
