//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ui_kalbe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produk
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produk()
        {
            this.Penjualans = new HashSet<Penjualan>();
        }
    
        public int intProductID { get; set; }
        public string txtProductCode { get; set; }
        public string txtProductName { get; set; }
        public Nullable<int> intQty { get; set; }
        public Nullable<decimal> decPrice { get; set; }
        public Nullable<System.DateTime> dtInserted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Penjualan> Penjualans { get; set; }
    }
}
